### ISSUE TITLE
请问我如何使用最新dev分支的sdk?

### ISSUE THREAD

**Issue by iperfectapp** [befovy/fijkplayer#47]
![image](https://user-images.githubusercontent.com/3021764/64245871-5b686100-cf3e-11e9-8edb-5516c2b09849.png)
是在这里添加dev分支的版本吗？

**Comment by befovy** [comment]
https://dart.dev/tools/pub/dependencies

参考文档内容。

```yml
dependencies:
  kittens:
    git:
      url: git://github.com/munificent/cats.git
      path: path/to/kittens
```
